## 组合挂起函数

本节包含几种组合挂起函数的方法。


### 默认顺序调用

我们定义如下两个挂起函数

```kotlin
suspend fun doSomethingUsefulOne(): Int {
    delay(1000L) // pretend we are doing something useful here
    return 13
}

suspend fun doSomethingUsefulTwo(): Int {
    delay(1000L) // pretend we are doing something useful here, too
    return 29
}
```

如果我们想顺序调用这两个挂起函数 — 先调用`doSomethingUsefulOne`,然后调用`doSomethingUsefulTwo`,然后对两者的返回结果求和。我们应该怎么做呢？

我们顺序调用即可，因为协程中的代码和常规代码一样，默认是顺序调用的。如下所示：

```kotlin
fun main() = runBlocking<Unit> {
    //注释1处
    val time = measureTimeMillis {
        val one = doSomethingUsefulOne()
        val two = doSomethingUsefulTwo()
        println("The answer is ${one + two}")
    }
    println("Completed in $time ms")
}
```

输出结果：
```
The answer is 42
Completed in 2017 ms
```

注释1处，measureTimeMillis是Kotlin库中定义的一个方法，用来测量一段代码块执行耗时时间。

默认顺序调用情况下，我们大约需要等待2000ms。

### 使用async实现并发调用

如果`doSomethingUsefulOne`和`doSomethingUsefulTwo`之间没有依赖关系，并且我们希望更快获取结果，那么我们可以使用`async`并发调用这两个方法。

在概念上，async 就类似于 launch。它启动了一个单独的协程，这是一个轻量级的线程并与其它所有的协程一起并发的工作。
不同之处在于 launch 返回一个 Job 并且不附带任何结果值，而 async 返回一个`Deferred<T>`—— 一个轻量级的非阻塞 future， 
这代表了一个将会在稍后提供结果的 promise。你可以使用`Deferred<T>#await()`方法来获取最终的执行结果`T`， 但是 Deferred 也是一个Job，所以如果需要的话，你可以取消它。


```kotlin
fun main() = runBlocking<Unit> {
    val time = measureTimeMillis {
        //注释1处
        val one = async { doSomethingUsefulOne() }
        val two = async { doSomethingUsefulTwo() }
        println("The answer is ${one.await() + two.await()}")
    }
    println("Completed in $time ms")
}
```
注释1处，我们使用`async`启动了两个协程来并发调用`doSomethingUsefulOne`和`doSomethingUsefulTwo`。

输出结果：
```
The answer is 42
Completed in 1017 ms
```

可以看到，我们大概只需要等待1000ms。因为这两个协程是并发执行的。

### 创建惰性启动的async

我们可以通过将`start`参数设置为`CoroutineStart.LAZY`来创建一个惰性启动的async。在这种模式下，只有当`Deferred<T>`的`#await()`方法或者
`Job`的`start`方法被调用的时候async才会真正启动协程。

```kotlin
fun main() = runBlocking<Unit> {
    val time = measureTimeMillis {
        //注释1处，创建惰性启动的async
        val one = async(start = CoroutineStart.LAZY) { doSomethingUsefulOne() }
        val two = async(start = CoroutineStart.LAZY) { doSomethingUsefulTwo() }
        //注释2处
        one.start() // start the first one
        two.start() // start the second one

        //注释3处
        println("The answer is ${one.await() + two.await()}")
    }
    println("Completed in $time ms")
}
```

注释1处，创建惰性启动的async。

注释2处，显式启动两个协程。

注释3处，等待两个协程执行完毕，获取结果。

输出结果：
```
The answer is 42
Completed in 1017 ms
```

**注意**，如果我们没有在注释2处分别调用两个协程的`start`方法，那么将会导致这两个协程顺序执行，因为`await`会启动协程并等待它执行完毕，这不是惰性启动的async的预期使用场景。
在值的计算涉及挂起函数的情况下，`async(start = CoroutineStart.LAZY)`这种使用方式是标准lazy函数的一种替代方式。

上面这段话目前只需要明白前半段就可以。哈哈。

```kotlin
fun main() = runBlocking<Unit> {
    val time = measureTimeMillis {
        //注释1处，创建惰性启动的async
        val one = async(start = CoroutineStart.LAZY) { doSomethingUsefulOne() }
        val two = async(start = CoroutineStart.LAZY) { doSomethingUsefulTwo() }
        //注释2处
        //one.start() // start the first one
        //two.start() // start the second one

        //注释3处
        println("The answer is ${one.await() + two.await()}")
    }
    println("Completed in $time ms")
}
```

注释1处，创建惰性启动的async。
注释2处，我们将显式启动两个协程的方法调用给注释掉。
注释3处，等待两个协程执行完毕，获取结果。

输出结果：
```
The answer is 42
Completed in 2031 ms
```

我们看到输出的时间果然变长了，说明两个协程确实是顺序执行的。

### 结构化并发和async

我们使用（### 使用async实现并发调用）段落中的例子来抽取一个函数并发的执行`doSomethingUsefulOne`和`doSomethingUsefulTwo`并返回两者调用结果的和。
因为`async`是`CoroutineScope`的一个扩展方法，所以我们需要将`async`置于一个`CoroutineScope`之中。`coroutineScope`函数提供了这样的功能。

```kotlin
suspend fun concurrentSum(): Int = coroutineScope {
    val one = async { doSomethingUsefulOne() }
    val two = async { doSomethingUsefulTwo() }
    one.await() + two.await()
}
```
这种情况下，如果在 concurrentSum 函数内部发生了错误，并且它抛出了一个异常， 所有在作用域中启动的协程都会被取消。

```kotlin
fun main() = runBlocking<Unit> {
    val time = measureTimeMillis {
        println("The answer is ${concurrentSum()}")
    }
    println("Completed in $time ms")
}

suspend fun concurrentSum(): Int = coroutineScope {
    //注释1处
    val one = async { doSomethingUsefulOne() }
    val two = async { doSomethingUsefulTwo() }
    one.await() + two.await()
}
```

注释1处，两个协程并发执行。

输出结果：

```
The answer is 42
Completed in 1017 ms
```

`Cancellation`始终通过协程的层次结构来进行传递:

```kotlin
fun main() = runBlocking<Unit> {//父协程
    try {
        failedConcurrentSum()
    } catch(e: ArithmeticException) {
        println("Computation failed with ArithmeticException")
    }
}

suspend fun failedConcurrentSum(): Int = coroutineScope {
    
    val one = async<Int> { 
        try {
            delay(Long.MAX_VALUE) // Emulates very long computation
            42
        } finally {
            println("First child was cancelled")
        }
    }
    //注释1处
    val two = async<Int> { 
        println("Second child throws an exception")
        throw ArithmeticException()
    }
    one.await() + two.await()
}

```

注释1处，当子协程`two`抛出异常的时候，子协程`one`和父协程都会被取消。













